### ISSUE TITLE
Incorrect MBC5 ROM bank select

### ISSUE THREAD

**Issue by jkotlinski** [OpenEmu/Gambatte-Core#2]
It seems like the MBC5 emulation does not allow selecting ROM bank 0. This is incorrect, ROM bank 0 is selectable in MBC5.

**Comment by shysaur** [comment]
This bug is not specific to our port of gambatte, and should be reported upstream to @sinamas, the original developer of gambatte. Sadly, it seems they have been inactive for a long time.
