### ISSUE TITLE
Aladdin 'Select' key issue

### ISSUE THREAD

**Issue by cnterr** [OpenEmu/Gambatte-Core#3]
In Aladdin rom (USA and EUR) 'Select' key for change between sword and apple not work.

**Comment by clobber** [comment]
Cannot replicate. Works just fine in both Game Boy and Game Boy Color versions.

Check your controls.

**Comment by cnterr** [comment]
Game Boy Color version works fine.
I tried Game Boy version in Gambatte core and standalone for PC, with a standard kayboard, and in Gambatte core for PS Classic, with its original joypad. Select key doesn't work.
In any other rom opened with Gambatte the select key works fine.
Aladdin GB with other cores for PC and PSC (ex. mGBA) works fine.

**Comment by clobber** [comment]
There is no input bug using the Gambatte core plugin with OpenEmu 2.0.8. Below is me pressing SELECT (Right Shift on my keyboard) to switch between the apple and the sword. It works.

<img width="942" alt="Screen Shot 2019-03-20 at 12 15 25 PM" src="https://user-images.githubusercontent.com/1303132/54705142-25f3c680-4b0a-11e9-9b36-0f22ed23918a.png">

<img width="942" alt="Screen Shot 2019-03-20 at 12 16 34 PM" src="https://user-images.githubusercontent.com/1303132/54705159-2f7d2e80-4b0a-11e9-9bf4-c50c9fc4f44d.png">

<img width="867" alt="Screen Shot 2019-03-20 at 12 20 42 PM" src="https://user-images.githubusercontent.com/1303132/54705358-9d295a80-4b0a-11e9-82e8-f53e8e500d1e.png">

Again, check your controls or check the [Input troubleshooting guide](https://github.com/OpenEmu/OpenEmu/wiki/Troubleshooting:-Input-problems) for your particular problem. Let's not waste any more time on this please.
