### ISSUE TITLE
Update libgambatte

### ISSUE THREAD

**Issue by jkotlinski** [OpenEmu/Gambatte-Core#4]
libgambatte seems to be pretty old. Upgrading would improve MBC5 cartridge support, which allows for compatibility with more games.

**Comment by clobber** [comment]
The Gambatte project was inactive for many years and it is only until very recently that the author picked it back up again. Once it is deemed stable and/or they make a new official release is when we will update our core port.

**Comment by clobber** [comment]
We've updated to the latest changes upstream. A core plugin release will be pushed after some more testing.
